### ISSUE TITLE
dublicate require statements

### ISSUE THREAD

**Issue by Guria** [VegaPublish/saga#7]
There are 2 identical statements `providers = require(config.auth.providersConfigPath)` in [applyStrategies.js](https://github.com/VegaPublish/saga/blob/f86384239f48e4378bf6c246f1737891ac2a798b/src/authentication/applyStrategies.js#L32-L39). First one before try block, and another one inside.
It looks like mistake for me. Second require will never catch error since it would be thrown on first one.

**Comment by simen** [comment]
That looks like the correct assessment. I'll correct it.
